services:
  backend:
    build: backend/
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
        - action: rebuild
          path: ./backend/src/test
    env_file:
      - .env
    ports:
      - "8080:8080"
  mysql:
    build: db/mysql
    env_file:
      - .env
  mongo:
    build: db/mongo
    env_file:
      - .env
  frontend:
    build: frontend
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
    ports:
      - "5173:5173"
