services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    env_file:
      - .env
  mysql:
    build: db/mysql
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
  mongo:
    build: db/mongo
    env_file:
      - .env
    volumes:
      - mongo_data:/data
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "80:80"
    
volumes:
  mysql_data:
    external: false
  mongo_data:
    external: false
