CREATE TABLE IF NOT EXISTS user (
  user_id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  user_name VARCHAR(255) NOT NULL UNIQUE,
  user_password CHAR(44) NOT NULL,
  token CHAR(44) NOT NULL UNIQUE,
  PRIMARY KEY(user_id)
) ENGINE = InnoDB;